name: required_environment
channels: 
    - conda-forge
    - underworldcode
dependencies:
    - stripy
    - litho1pt0
    - quagmire
    - cartopy
    - obspy
    - pandas
    - pip 
    - jupyterlab>=2 
    - jupytext
    - libiconv  # Not sure why this is not a dependency of lxml (conda bug)



