name: base
channels: 
    - conda-forge
    - geo-down-under
dependencies:
    - stripy
    - litho1pt0
    - quagmire
    - cartopy
    - obspy
    - pandas
    # - pip 
    # - libiconv  # Not sure why this is not a dependency of lxml (conda bug)
    # - jupytext
    
    



