# Book settings
title: EMSC 3002
author: Louis Moresi 
logo: Figures/AuWorldEQ.jpg
exclude_patterns: ["README.md", "Notes/*", "Scripts/*", "Lectures/*.reveal.md"]

latex:
  latex_documents:
    targetname: JupyterBookHub.tex

html:
#  home_page_in_navbar option: true
  use_repository_button: true
  comments:
    hypothesis: true

parse:
  myst_extended_syntax: true

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_extra_path: ['Lectures/static_slides']


repository:
  url         : https://github.com/ANU-RSES-Education/EMSC-3002  # Online location of this book
  branch      : master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  # jupyterhub_url: "https://demon.underworldcloud.org"  # The URL for your JupyterHub. 
  binderhub_url:  "https://mybinder.org"  # The URL of the BinderHub (e.g., https://mybinder.org)
  notebook_interface: "classic" # "jupyterlab" or "classic"


execute:
  # exclude_patterns:
  #   - File.ipynb
  execute_notebooks: 'off'
  allow_errors : true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.


bibtex_bibfiles:
   - JupyterBook.bib
