name: Initialise tljh

on:
  push:
    paths:
      - 'ServerID.md'                         # change the ID file
      - .github/workflows/install_tljh.yml    # or this file

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Install sshpass
      run: |
        sudo apt-get install -y sshpass
      

    # Updates packages / reconfig tljh then reloads just in case
    - name: Install tljh from scratch then update the packages
      env:  
        SSHPASS:       ${{ secrets.DROPLET_PASS }} 
        HUBADMIN:      ${ ${{ secrets.HUBADMIN_USER }} := "rses_hubadmin" }
        HUBADMIN_PASS: ${ ${{ secrets.HUBADMIN_PASSWORD }} := "t4$%^&*****hdhjbviugrvbjfeuvgyhjbufewovgci" }
        REMOTE_SH:     "sudo -E sshpass -e ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }}"
      run: |
        $REMOTE_SH "hostname"
        $REMOTE_SH "curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo python3 -  --admin $HUBADMIN:$HUBADMIN_PASS" 
        $REMOTE_SH "sudo tljh-config reload hub"

        sudo -E sshpass -e scp packages.yml root@${{ secrets.DROPLET_IP }}:packages.yml
        $REMOTE_SH 'sudo -E /opt/tljh/user/bin/conda env update -n base --file packages.yml'

        # Notebook extensions are handled like this 
        $REMOTE_SH 'sudo -E /opt/tljh/user/bin/pip install jupyter_contrib_nbextensions'
        $REMOTE_SH 'sudo -E /opt/tljh/user/bin/jupyter contrib nbextension install --sys-prefix'
        $REMOTE_SH 'sudo -E /opt/tljh/user/bin/jupyter nbextension enable freeze/main'


        